// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYvsxfdq8pSqMpdIgMDOaYICJxynYGu2s',
    appId: '1:216359645268:web:3ada1aab7d3712b26d3dc1',
    messagingSenderId: '216359645268',
    projectId: 'verbs-ac039',
    authDomain: 'verbs-ac039.firebaseapp.com',
    storageBucket: 'verbs-ac039.appspot.com',
    measurementId: 'G-70M5VLMQ6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf1IOYpX7pTrzzx4alDum9drKpiKm75Ck',
    appId: '1:216359645268:android:1a3a90d5d5607f736d3dc1',
    messagingSenderId: '216359645268',
    projectId: 'verbs-ac039',
    storageBucket: 'verbs-ac039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4iHAJLCEd0KAGEXH7BovY-X0-2l6zEO4',
    appId: '1:216359645268:ios:a18c02fe2a36bb866d3dc1',
    messagingSenderId: '216359645268',
    projectId: 'verbs-ac039',
    storageBucket: 'verbs-ac039.appspot.com',
    iosClientId: '216359645268-qsgkffk43qt1s1if7ndke814t4n517e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.irrefularVerbs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYvsxfdq8pSqMpdIgMDOaYICJxynYGu2s',
    appId: '1:216359645268:web:40cf9eb47925cca46d3dc1',
    messagingSenderId: '216359645268',
    projectId: 'verbs-ac039',
    authDomain: 'verbs-ac039.firebaseapp.com',
    storageBucket: 'verbs-ac039.appspot.com',
    measurementId: 'G-69JWRD9S3L',
  );
}
